apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: nodepool-infra
  namespace: test-np
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
spec:
  config:
    - name: infra-dynamic-node
